---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    # Update packages and Install requirements
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes

    - name: Install python pip3
      apt: name=python3-pip state=present
      become: yes

    # Install and configure NGINX
    - name: Instaling nginx
      apt: name=nginx state=present
      become: yes

    - name: Starting  nginx
      service:
          name: nginx
          state: started
      become: yes

    - name: Copy the nginx config file (reverse proxy)
      copy:
        src: reverse_proxy.conf
        dest: /etc/nginx/sites-available/reverse_proxy.conf
      become: yes

    - name: Create symlink (reverse proxy)
      file:
        src: /etc/nginx/sites-available/reverse_proxy.conf
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    # Install and Configure Docker form docker.io (ubuntu)
    - name: Install docker.io
      apt: name=docker.io state=present

    - name: Starting docker
      service:
          name: docker
          state: started
      become: yes

    - name: Install Docker Module for Python
      pip:
        name: docker

    # Pull image from the Docker Hub
    - name: Pull bharathshetty4/supermario docker image
      docker_image:
        name: "bharathshetty4/supermario"
        source: pull

    # Configure supermario startup script and start it
    - name: Copy the supermario startup script to systemd
      copy:
        src: supermario.service
        dest: /etc/systemd/system/supermario.service
      become: yes

    - name: Starting supermario
      service:
          name: supermario
          state: started
          enabled: yes
      become: yes
